# -*- coding: utf-8 -*-
"""GHDS-simulation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ooZMYsbfosdAVhawtq2wCHsJi59GDMVO
"""

import numpy as np
import matplotlib.pyplot as plt

xi = 1.0
c = 1.0
hbar = 1.0
Gamma = 0.08
kappa = 0.4

D = 3
s_max = 1.2
b = 0.6
k1 = 0.8
k2 = 0.8
omega = 1.0
alpha = 0.3
V0 = 2.0

theta_0 = np.pi / 2.0 + 0.45
phi_0 = 0.0
s_0 = 0.0
sigma_theta = 0.12
sigma_phi = 0.20
sigma_s = 0.25
v_init = -0.55 * c

N_theta = 35
N_phi = 25
N_s = 17
N_steps = 250
dt = 0.010

theta_1d = np.linspace(np.pi / 2.0 - 0.75, np.pi / 2.0 + 0.75, N_theta)
phi_1d = np.linspace(-0.8, 0.8, N_phi)
s_1d = np.linspace(-s_max, s_max, N_s)

dtheta = theta_1d[1] - theta_1d[0]
dphi = phi_1d[1] - phi_1d[0]
ds = s_1d[1] - s_1d[0]

theta_3d, phi_3d, s_3d = np.meshgrid(theta_1d, phi_1d, s_1d, indexing='ij')

q1 = np.sqrt(D) * np.sin(theta_3d) * np.cos(phi_3d)
q2 = np.sqrt(D) * np.sin(theta_3d) * np.sin(phi_3d)
q3 = np.sqrt(D) * np.cos(theta_3d)

sin_theta = np.sin(theta_3d)
sin2_theta = sin_theta**2
cot_theta = 1.0 / np.tan(theta_3d)
dV = D * sin_theta * (dtheta * dphi * ds)

V = (-b * q3 + 0.5 * (k1 * q1**2 - k2 * q2**2)) * np.exp(-alpha * s_3d) + 0.5 * (omega**2) * (s_3d**2) + V0

def compute_derivatives(f):
    d_theta = np.zeros_like(f)
    d_theta[1:-1, :, :] = (f[2:, :, :] - f[:-2, :, :]) / (2.0 * dtheta)
    d_theta[0, :, :] = (f[1, :, :] - f[0, :, :]) / dtheta
    d_theta[-1, :, :] = (f[-1, :, :] - f[-2, :, :]) / dtheta

    d2_theta = np.zeros_like(f)
    d2_theta[1:-1, :, :] = (f[2:, :, :] - 2.0 * f[1:-1, :, :] + f[:-2, :, :]) / (dtheta**2)
    d2_theta[0, :, :] = (f[1, :, :] - f[0, :, :]) / (dtheta**2)
    d2_theta[-1, :, :] = (f[-2, :, :] - f[-1, :, :]) / (dtheta**2)

    d_phi = np.zeros_like(f)
    d_phi[:, 1:-1, :] = (f[:, 2:, :] - f[:, :-2, :]) / (2.0 * dphi)
    d_phi[:, 0, :] = (f[:, 1, :] - f[:, 0, :]) / dphi
    d_phi[:, -1, :] = (f[:, -1, :] - f[:, -2, :]) / dphi

    d2_phi = np.zeros_like(f)
    d2_phi[:, 1:-1, :] = (f[:, 2:, :] - 2.0 * f[:, 1:-1, :] + f[:, :-2, :]) / (dphi**2)
    d2_phi[:, 0, :] = (f[:, 1, :] - f[:, 0, :]) / (dphi**2)
    d2_phi[:, -1, :] = (f[:, -2, :] - f[:, -1, :]) / (dphi**2)

    d_s = np.zeros_like(f)
    d_s[:, :, 1:-1] = (f[:, :, 2:] - f[:, :, :-2]) / (2.0 * ds)
    d_s[:, :, 0] = (f[:, :, 1] - f[:, :, 0]) / ds
    d_s[:, :, -1] = (f[:, :, -1] - f[:, :, -2]) / ds

    d2_s = np.zeros_like(f)
    d2_s[:, :, 1:-1] = (f[:, :, 2:] - 2.0 * f[:, :, 1:-1] + f[:, :, :-2]) / (ds**2)
    d2_s[:, :, 0] = (f[:, :, 1] - f[:, :, 0]) / (ds**2)
    d2_s[:, :, -1] = (f[:, :, -2] - f[:, :, -1]) / (ds**2)

    return d_theta, d_phi, d_s, d2_theta, d2_phi, d2_s

def laplacian_Q(f):
    d_theta, _, _, d2_theta, d2_phi, d2_s = compute_derivatives(f)
    return (1.0 / D) * (d2_theta + cot_theta * d_theta + (1.0 / sin2_theta) * d2_phi) + d2_s

def grad_inner_product(phi_f, psi_f):
    dth_phi, dph_phi, ds_phi, _, _, _ = compute_derivatives(phi_f)
    dth_psi, dph_psi, ds_psi, _, _, _ = compute_derivatives(psi_f)
    return (1.0 / D) * (dth_phi * dth_psi + (1.0 / sin2_theta) * dph_phi * dph_psi) + ds_phi * ds_psi

def grad_norm_sq(f):
    d_th, d_ph, d_s, _, _, _ = compute_derivatives(f)
    return (1.0 / D) * np.abs(d_th)**2 + (1.0 / (D * sin2_theta)) * np.abs(d_ph)**2 + np.abs(d_s)**2

f0 = np.exp(-0.5 * (
    ((theta_3d - theta_0)**2) / (sigma_theta**2) +
    (sin2_theta * ((phi_3d - phi_0)**2)) / (sigma_phi**2) +
    ((s_3d - s_0)**2) / (sigma_s**2)
))
Z0 = np.sum((f0**2) * dV)
sqrt_rho0 = f0 / np.sqrt(Z0)

lap_sqrt_rho0 = laplacian_Q(sqrt_rho0)
reg_mask = sqrt_rho0 > 1e-6 * np.max(sqrt_rho0)
Q_init = np.zeros_like(sqrt_rho0)
Q_init[reg_mask] = - (hbar**2 / (2.0 * xi * sqrt_rho0[reg_mask])) * lap_sqrt_rho0[reg_mask]

idx_theta0 = int(np.argmin(np.abs(theta_1d - theta_0)))
idx_phi0 = int(np.argmin(np.abs(phi_1d - phi_0)))
idx_s0 = int(np.argmin(np.abs(s_1d - s_0)))
Q_init_y0 = Q_init[idx_theta0, idx_phi0, idx_s0]
V_y0 = V[idx_theta0, idx_phi0, idx_s0]

radicand_p = 1.0 + (2.0 * (V_y0 + Q_init_y0)) / (xi * (c**2))
p_init = (xi * v_init / np.sqrt(1.0 - (v_init / c)**2)) * np.sqrt(radicand_p)

S0 = p_init * np.sqrt(D) * (theta_3d - theta_0)
Psi_0 = sqrt_rho0 * np.exp(1j * S0 / hbar)

radicand_p0 = np.maximum(0.0, (xi**2) * (c**2) + (p_init**2) + (2.0 * xi / (c**2)) * (V + Q_init))
p0 = -np.sqrt(radicand_p0)

dt_Psi_0 = (1j * c * p0 / hbar) * Psi_0
phi_0_field = np.zeros_like(sqrt_rho0)
dt_phi_0_field = np.zeros_like(sqrt_rho0)

rho_init = np.sum(np.abs(Psi_0)**2 * ds, axis=2)

def eval_rhs(Psi_curr, Pi_Psi_curr, phi_curr, Pi_phi_curr):
    lap_Psi = laplacian_Q(Psi_curr)
    lap_phi = laplacian_Q(phi_curr)
    inner_grad = grad_inner_product(phi_curr, Psi_curr)
    exp_2phi = np.exp(2.0 * phi_curr)
    exp_4phi = np.exp(4.0 * phi_curr)
    rho_curr = np.abs(Psi_curr)**2

    rhs_Psi = Pi_Psi_curr
    pot_term = ((xi**2) * (c**4) + 2.0 * xi * (c**2) * V) / (hbar**2)
    rhs_Pi_Psi = (
        (c**2) * (lap_Psi + 2.0 * inner_grad)
        - (2.0 * Pi_phi_curr + Gamma * exp_2phi) * Pi_Psi_curr
        - exp_2phi * pot_term * Psi_curr
    )

    rhs_phi = Pi_phi_curr
    rhs_Pi_phi = (
        (c**2) * (lap_phi - ((xi * c / hbar)**2) * phi_curr)
        + kappa * xi * (c**4) * exp_4phi * rho_curr
    )
    return rhs_Psi, rhs_Pi_Psi, rhs_phi, rhs_Pi_phi

idx_apex_theta = int(np.argmin(np.abs(theta_1d - np.pi / 2.0)))
idx_apex_phi = int(np.argmin(np.abs(phi_1d - 0.0)))

time_array = np.zeros(N_steps)
avg_v_over_c = np.zeros(N_steps)
rho_apex_history = np.zeros(N_steps)
phi_apex_history = np.zeros(N_steps)
noether_ratio = np.zeros(N_steps)
hamiltonian_ratio = np.zeros(N_steps)

theta_cen_history = np.zeros(N_steps)
phi_cen_history = np.zeros(N_steps)
rho_2d_history = np.zeros((N_steps, N_theta, N_phi))

def compute_diagnostics(Psi_val, Pi_Psi_val, phi_val, Pi_phi_val):
    exp_2phi = np.exp(2.0 * phi_val)
    rho_val = np.abs(Psi_val)**2

    j0 = - (hbar / (xi * (c**2))) * exp_2phi * np.imag(np.conj(Psi_val) * Pi_Psi_val)
    dth_psi, dph_psi, ds_psi, _, _, _ = compute_derivatives(Psi_val)
    j_theta = (hbar / xi) * np.imag(np.conj(Psi_val) * dth_psi)
    j_phi = (hbar / xi) * np.imag(np.conj(Psi_val) * dph_psi)
    j_s = (hbar / xi) * np.imag(np.conj(Psi_val) * ds_psi)

    norm_j = np.sqrt((j_theta**2) / D + (j_phi**2) / (D * sin2_theta) + j_s**2)

    int_norm_j = np.sum(norm_j * dV)
    int_j0 = np.sum(j0 * dV)
    v_ratio = int_norm_j / (int_j0 + 1e-15)

    rho_apex = (1.0 / (2.0 * s_max)) * np.sum(rho_val[idx_apex_theta, idx_apex_phi, :] * ds)
    phi_apex = (1.0 / (2.0 * s_max)) * np.sum(phi_val[idx_apex_theta, idx_apex_phi, :] * ds)

    grad_psi_sq = grad_norm_sq(Psi_val)
    grad_phi_sq = grad_norm_sq(phi_val)
    H_density = (
        (hbar**2 / (2.0 * xi * (c**2))) * np.abs(Pi_Psi_val)**2
        + (hbar**2 / (2.0 * xi)) * grad_psi_sq
        + exp_2phi * (0.5 * xi * (c**2) + V) * rho_val
        + (1.0 / (2.0 * kappa * (c**2))) * (Pi_phi_val**2)
        + (1.0 / (2.0 * kappa)) * grad_phi_sq
        + ((xi**2) * (c**2) / (2.0 * kappa * (hbar**2))) * (phi_val**2)
    )
    H_val = np.sum(H_density * dV)

    tot_rho = np.sum(rho_val * dV)
    theta_cen = np.sum(theta_3d * rho_val * dV) / (tot_rho + 1e-15)
    phi_cen = np.sum(phi_3d * rho_val * dV) / (tot_rho + 1e-15)

    return v_ratio, rho_apex, phi_apex, int_j0, H_val, theta_cen, phi_cen

Psi = Psi_0.copy()
Pi_Psi = dt_Psi_0.copy()
phi = phi_0_field.copy()
Pi_phi = dt_phi_0_field.copy()

N0_val = 0.0
H0_val = 0.0

for step in range(N_steps):
    t_curr = step * dt
    time_array[step] = t_curr

    v_rat, r_ap, p_ap, N_curr, H_curr, th_c, ph_c = compute_diagnostics(Psi, Pi_Psi, phi, Pi_phi)
    if step == 0:
        N0_val = N_curr
        H0_val = H_curr

    avg_v_over_c[step] = v_rat
    rho_apex_history[step] = r_ap
    phi_apex_history[step] = p_ap
    noether_ratio[step] = N_curr / N0_val
    hamiltonian_ratio[step] = H_curr / H0_val
    theta_cen_history[step] = th_c
    phi_cen_history[step] = ph_c
    rho_2d_history[step] = np.sum(np.abs(Psi)**2 * ds, axis=2)

    k1_Psi, k1_Pi_Psi, k1_phi, k1_Pi_phi = eval_rhs(Psi, Pi_Psi, phi, Pi_phi)
    k2_Psi, k2_Pi_Psi, k2_phi, k2_Pi_phi = eval_rhs(
        Psi + 0.5 * dt * k1_Psi, Pi_Psi + 0.5 * dt * k1_Pi_Psi,
        phi + 0.5 * dt * k1_phi, Pi_phi + 0.5 * dt * k1_Pi_phi
    )
    k3_Psi, k3_Pi_Psi, k3_phi, k3_Pi_phi = eval_rhs(
        Psi + 0.5 * dt * k2_Psi, Pi_Psi + 0.5 * dt * k2_Pi_Psi,
        phi + 0.5 * dt * k2_phi, Pi_phi + 0.5 * dt * k2_Pi_phi
    )
    k4_Psi, k4_Pi_Psi, k4_phi, k4_Pi_phi = eval_rhs(
        Psi + dt * k3_Psi, Pi_Psi + dt * k3_Pi_Psi,
        phi + dt * k3_phi, Pi_phi + dt * k3_Pi_phi
    )

    Psi += (dt / 6.0) * (k1_Psi + 2.0 * k2_Psi + 2.0 * k3_Psi + k4_Psi)
    Pi_Psi += (dt / 6.0) * (k1_Pi_Psi + 2.0 * k2_Pi_Psi + 2.0 * k3_Pi_Psi + k4_Pi_Psi)
    phi += (dt / 6.0) * (k1_phi + 2.0 * k2_phi + 2.0 * k3_phi + k4_phi)
    Pi_phi += (dt / 6.0) * (k1_Pi_phi + 2.0 * k2_Pi_phi + 2.0 * k3_Pi_phi + k4_Pi_phi)

plt.rcParams['axes.edgecolor'] = '#333333'
plt.rcParams['axes.linewidth'] = 1.0

fig, axes = plt.subplots(2, 2, figsize=(14, 11), dpi=300)

ax_a = axes[0, 0]
ax_a.plot(time_array, avg_v_over_c, color='#1f77b4', lw=2.2, label=r'$\langle\|\mathbf{v}\|\rangle / c$')
ax_a.axhline(1.0, color='#d62728', linestyle='--', lw=1.8, label=r'Causality Bound ($c=1.0$)')
ax_a.set_title('(a) Relativistic Causality Bound\n' + r'$\langle\|\mathbf{v}\|\rangle/c < 1$', fontsize=11, fontweight='bold', pad=10)
ax_a.set_xlabel('Time $t$', fontsize=10)
ax_a.set_ylabel(r'Velocity Ratio $\langle\|\mathbf{v}\|\rangle / c$', fontsize=10)
ax_a.set_ylim(0.0, 1.15)
ax_a.grid(True, linestyle=':', alpha=0.6)
ax_a.legend(loc='lower right', frameon=True, fontsize=9)

ax_b = axes[0, 1]
norm_rho_apex = rho_apex_history / (np.max(rho_apex_history) + 1e-15)
norm_phi_apex = phi_apex_history / (np.max(phi_apex_history) + 1e-15)

idx_peak_rho = int(np.argmax(norm_rho_apex))
idx_peak_phi = int(np.argmax(norm_phi_apex))
t_peak_rho = time_array[idx_peak_rho]
t_peak_phi = time_array[idx_peak_phi]
delta_tau = t_peak_phi - t_peak_rho

idx_step_delay = idx_peak_phi - idx_peak_rho
idx_snap = min(N_steps - 1, idx_peak_phi + idx_step_delay)
t_snap = time_array[idx_snap]
rho_snap = rho_2d_history[idx_snap]

ax_b.plot(time_array, norm_rho_apex, color='#2ca02c', lw=2.0, label=r'Fluid Density $\rho_{\mathrm{apex}}(t)$')
ax_b.plot(time_array, norm_phi_apex, color='#9467bd', lw=2.0, label=r'Metric Wave $\phi_{\mathrm{apex}}(t)$')
ax_b.axvline(t_peak_rho, color='#2ca02c', linestyle=':', lw=1.2, alpha=0.7)
ax_b.axvline(t_peak_phi, color='#9467bd', linestyle=':', lw=1.2, alpha=0.7)
ax_b.annotate(
    f'Retardation\n$\\delta\\tau = {delta_tau:.2f} > 0$',
    xy=(t_peak_phi, 0.8), xytext=(t_peak_phi + 0.35, 0.75),
    arrowprops=dict(arrowstyle='->', color='#333333', lw=1.2),
    fontsize=9, fontweight='bold', bbox=dict(boxstyle='round,pad=0.3', facecolor='#f0f0f0', edgecolor='#cccccc')
)
ax_b.set_title('(b) Hyperbolic Metric Retardation\n' + r'$\delta\tau = t_\phi - t_\rho > 0$', fontsize=11, fontweight='bold', pad=10)
ax_b.set_xlabel('Time $t$', fontsize=10)
ax_b.set_ylabel('Normalized Amplitude', fontsize=10)
ax_b.set_ylim(-0.05, 1.2)
ax_b.grid(True, linestyle=':', alpha=0.6)
ax_b.legend(loc='upper right', frameon=True, fontsize=9)

ax_c = axes[1, 0]
ax_c.plot(time_array, hamiltonian_ratio, color='#ff7f0e', lw=2.2, label=r'Hamiltonian $\mathcal{H}(t)/\mathcal{H}_0$')
ax_c.plot(time_array, noether_ratio, color='#8c564b', lw=2.0, linestyle='-.', label=r'Noether $\mathcal{N}(t)/\mathcal{N}_0$')
ax_c.set_title('(c) Herglotz Contact Dissipation\n' + r'$\mathcal{H}(t)/\mathcal{H}_0 \text{ & } \mathcal{N}(t)/\mathcal{N}_0$', fontsize=11, fontweight='bold', pad=10)
ax_c.set_xlabel('Time $t$', fontsize=10)
ax_c.set_ylabel('Normalized Ratio', fontsize=10)
ax_c.set_ylim(0.0, 1.1)
ax_c.grid(True, linestyle=':', alpha=0.6)
ax_c.legend(loc='upper right', frameon=True, fontsize=9)

ax_d = axes[1, 1]
Phi_grid, Theta_grid = np.meshgrid(phi_1d, theta_1d)

levels = np.linspace(0.0, np.max(rho_snap), 20)
cntr = ax_d.contourf(Phi_grid, Theta_grid, rho_snap, levels=levels, cmap='viridis')
fig.colorbar(cntr, ax=ax_d, label=rf'Density $\rho(\theta, \varphi)$ at $t={t_snap:.2f}$ ($t_\phi + \delta\tau$)', pad=0.03)

max_rho_init = np.max(rho_init)
ax_d.contour(
    Phi_grid, Theta_grid, rho_init,
    levels=[0.2 * max_rho_init, 0.5 * max_rho_init, 0.8 * max_rho_init],
    colors='white', linestyles='--', linewidths=1.2, alpha=0.7
)

ax_d.plot(
    phi_cen_history[:idx_snap + 1], theta_cen_history[:idx_snap + 1],
    color='white', lw=2.0,
    label=r'Centroid Trajectory $\mathbf{y}_{\mathrm{cen}}(t)$'
)

ax_d.plot(phi_0, theta_0, marker='o', color='white', markeredgecolor='black', markersize=8, label=r'Initial Center $\mathbf{y}_0$')
ax_d.plot(0.0, np.pi / 2.0, marker='X', color='red', markersize=10, label=r'Saddle Apex $(\pi/2, 0)$')

ax_d.set_title(rf'(d) Coherent Saddle Penetration' '\n' rf'Centroid Traversal & Soliton Localization ($t={t_snap:.2f}$)', fontsize=11, fontweight='bold', pad=10)
ax_d.set_xlabel(r'Coordinate $\varphi$', fontsize=10)
ax_d.set_ylabel(r'Coordinate $\theta$', fontsize=10)
ax_d.legend(loc='upper left', frameon=True, facecolor='white', framealpha=0.8, fontsize=8)

plt.tight_layout()
output_filename = 'ghds-simulation.pdf'
plt.savefig(output_filename, dpi=300)
plt.show()